version: "3.8"
services:
  nginx:
    image: nginx:1.20.0-alpine
    labels:
      - app=nginx
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
      rollback_config:
        parallelism: 1
        order: start-first
      restart_policy:
        condition: any
        delay: 1s
        window: 10s
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - mode: host
        protocol: tcp
        published: 80
        target: 80
      - mode: host
        protocol: tcp
        published: 443
        target: 443
    networks:
      - app
  app:
    labels:
      - app=app
    image: $APP_IMAGE
    networks:
      - app
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
      rollback_config:
        parallelism: 1
        order: start-first
      restart_policy:
        condition: any
        delay: 1s
        window: 10s
    env_file: app.env

networks:
  app:
    external: true