version: "3.8"
services:
  neo4j:
    image: neo4j:4.0.3
    volumes:
      - neo4j-data:/data
    networks:
      - app
    environment:
      NEO4J_AUTH: neo4j/test
      NEO4J_dbms_logs_debug_level: DEBUG
  redis:
    labels:
      app: redis
    image: redis:6.0.9-alpine3.12
    command: redis-server --requirepass $REDIS_PASSWORD
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    deploy:
      replicas: 1
    networks:
      - app
    volumes:
      - redis-data:/data

volumes:
  neo4j-data:
  redis-data:
networks:
  app:
    external: true