version: "3.8"
services:
  mysql:
    labels:
      app: mysql
    image: mysql:8.0.24
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      - app
    command: --default-authentication-plugin=mysql_native_password --wait_timeout=28800
    environment:
      MYSQL_ROOT_PASSWORD: app
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_HOST: '%'
    deploy:
      replicas: 1
    volumes:
      - mysql-data:/var/lib/mysql
  redis:
    labels:
      app: redis
    image: redis:6.0.9-alpine3.12
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    deploy:
      replicas: 1
    networks:
      - app
    volumes:
      - redis-data:/data

volumes:
  mysql-data:
  redis-data:
networks:
  app:
    external: true