on:
  push:
    tags:
      - "*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Deploy app'
        uses: appleboy/ssh-action@master
        env:
          NEO4J_PASSWORD: ${{ secrets.NEO4J_PASSWORD }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
          JWT_KEY: ${{ secrets.JWT_KEY }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          envs: NEO4J_PASSWORD,REDIS_PASSWORD,MAIL_PASSWORD,JWT_KEY
          script: sh -c "cd BackDeployer && git checkout master && git pull && NEO4J_PASSWORD=${{ secrets.NEO4J_PASSWORD }} REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }} MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }} JWT_KEY=${{ secrets.JWT_KEY }} bash deploy.sh"