on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Login to azure'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: 'Checkout repo code'
        uses: actions/checkout@v2
      - name: 'Run deploy script'
        run: bash deploy.sh